### ISSUE TITLE
Bot can't type capital letters

### ISSUE THREAD

**Issue by siegfrieeed87** [kotekpsotek/awesome-instaling#3]
Hey i got an issue with bot, after a translation it will type in small letters only so its getting stucked on "blue". I don't have a idea to fix it can you maybe propose something? Maybe a small change in code. (Im doing installing in Deustch leanguage so thats capital letters are needed 

Pozdrawiam

**Comment by kotekpsotek** [comment]
Welcome. I understand your need and If you would like to perform changes by yourself you should try do change by replace function  ```def translate_word_by_use_google_tr(word)``` located in [instaling.py file](https://github.com/kotekpsotek/awesome-instaling/blob/master/instaling.py) in **line** span ***321-326*** by replace currently existsing function to following: 

(Choose one option which match best for your need)

**If you need capital letters on the begining of typing word:**
```python
def translate_word_by_use_google_tr(word: str):
    translator_machine = googletrans.Translator()
    translator_word_lang_detect = translator_machine.detect(word).lang
    translated_word = translator_machine.translate(word, dest="en", src=translator_word_lang_detect).text # get the translated word text
    starts_with_capital = translated_word.capitalize() # first letter from word is capitalized other are still lower-cased
    return starts_with_capital
```

**If you need all words from i.e: words set/sentence which starts with capital letter**
```python
def translate_word_by_use_google_tr(word: str):
    translator_machine = googletrans.Translator()
    translator_word_lang_detect = translator_machine.detect(word).lang
    translated_word = translator_machine.translate(word, dest="en", src=translator_word_lang_detect).text # get the translated word text
    slicex = translated_word.split(" ")
    for id in range(0, len(slicex)):
        capitalized_word = slicex[id].capitalize()
        slicex[id] = capitalized_word
    word = " ".join(slicex)
    return word
```

Thanks for issue 🙂!

**Comment by KacperK4** [comment]
I have the same problem, but if i replace this lines a new error has appeared.
![image](https://user-images.githubusercontent.com/102327280/203820419-4825099d-aa24-478c-982c-7f9a8bb1708c.png)

**Comment by kotekpsotek** [comment]
I updated my pointer for both use cases, but you must also perform 2 additional changes in lines **416** and **430**, hence replace this couple of lines code to:
```Python
local_translation = translate_word_by_use_google_tr(word_to_translate)
``` 
(without reference to **.text** property from **Translated** object)

**Comment by KacperK4** [comment]
It's still not work. Refine your code and put it on the repository. I will download it again.
Update the Instaling.py

**Comment by kotekpsotek** [comment]
I quote my last comment "I updated my pointer" (I thought about 1st pointer) so you must too. Next you must update 2 lines (from this comment https://github.com/kotekpsotek/awesome-instaling/issues/3#issuecomment-1326785907). After all everything works fine. If you have got another error then "Attribute error" put here backtrace
